version: '2.4'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 4000:4000
    environment:
      - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
    volumes:
      - ./:/app
      - /app/deps
      - /app/_build
      - /app/assets/node_modules
  # prod:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/prod.Dockerfile
  #   ports:
  #     - 4001:4001
  #   environment:
  #     - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
  #     - PORT=4001
  #     - HOSTNAME=localhost
  #     - SECRET_KEY_BASE=3akuyHrOK2nzGT/zYnsBYjZG9c9AxmqDiqNwpyRCkYZ5HdsaEnS3fx0eU5pW6sCw
